"""add user audit fields to controls

Revision ID: 9ea3bd04db20
Revises: bbc827a311bf
Create Date: 2026-07-07 16:13:42.863277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea3bd04db20'
down_revision: Union[str, Sequence[str], None] = 'bbc827a311bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('controls', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_controls_created_by_id_users",
        "controls",
        "users",
        ["created_by_id"],
        ["id"],
    )

    op.create_foreign_key(
        "fk_controls_updated_by_id_users",
        "controls",
        "users",
        ["updated_by_id"],
        ["id"],
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_controls_updated_by_id_users",
        "controls",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_controls_created_by_id_users",
        "controls",
        type_="foreignkey",
    )
    op.drop_column('controls', 'updated_by_id')
    op.drop_column('controls', 'created_by_id')
    # ### end Alembic commands ###
